[graph]
all-features = true

[advisories]
unmaintained = "none"

[bans]
multiple-versions = "allow" #TODO
deny = [
    { crate = "aws-lc-rs", reason = "often fails to compile", use-instead = "ring" },
]
